### ISSUE TITLE
Fix playing failure voice line after achieving victory in an instance

### ISSUE THREAD

**Issue by rekyuu** [rekyuu/StanleyParableXiv#1]

**Comment by rekyuu** [comment]
f5df21743d2b5ef702e8b420c80b55e63a2c4e2a

**Comment by keysmashes** [comment]
fwiw, this appears to not work properly (or we mean different things by "instance") – I just completed the solo duty "The Hunt for Omega" and got a failure voiceline, with plugin version 1.2.3.0
