### ISSUE TITLE
doesnt work for me on a new install of the plugin. 

### ISSUE THREAD

**Issue by shalolaauthor** [rekyuu/StanleyParableXiv#20]
i press test a bunch of time and no sound ever came out. and also no narration during the gameplay

**Comment by rekyuu** [comment]
Hey there,

Can you confirm that this happens on different volume settings (IE, try manual volume over binding to game volume) and boost levels? 

Additionally, the asset files will need about 100MB of free disk space to initially download and extract. If they were downloaded successfully, you will see them downloaded to:

- Windows: `%appdata%\XIVLauncher\pluginConfigs\StanleyParableXiv\assets`
- Linux: `~/.xlcore/pluginConfigs/StanleyParableXiv/assets`

I've pushed some updates to the testing branch today to provide feedback to the user if there is a disk space issue, but it's worth a check in the meantime.

**Comment by shalolaauthor** [comment]
![image](https://user-images.githubusercontent.com/124796924/227756309-a8260aab-50d6-490e-b71b-32129311881d.png)
everything works when i play the sound bite manually. sorry just got the time to play again.
