### ISSUE TITLE
Plays through non-default speaker

### ISSUE THREAD

**Issue by pinoybear** [rekyuu/StanleyParableXiv#24]
I have my default speakers set to my onboard sound card which I have my headphones plugged into. FFXIV is playing all its sound through the headphones as expected. The plugin is playing through my USB speakers.

**Comment by rekyuu** [comment]
Ensure your USB headphones aren't marked as the default audio device. The NAudio library uses the default audio device on instantiation. 

https://github.com/naudio/NAudio/blob/master/Docs/OutputDeviceTypes.md#waveoutevent--waveout
https://github.com/naudio/NAudio/blob/master/NAudio.WinMM/WaveOutEvent.cs#L45
